import {
  Sparkles,
  Cloud,
  ZoomIn,
  Camera,
  Sun,
  Eye,
  Film,
  Image,
  Waves,
  Lightbulb,
  Zap,
  Activity,
  Users,
  Boxes,
  WandSparkles,
  MemoryStick,
  Layers,
  MapPin,
  Shield,
  Gauge,
  FlaskConical,
  Minus,
  Compass,
  PanelBottom,
  Mountain,
  Accessibility,
  Wrench,
  Keyboard,
  MousePointer2,
  Volume2,
} from "lucide-react";
export const categories = [
  { name: "Visuals", icon: Sparkles },
  { name: "Performance", icon: Zap },
  { name: "HUD", icon: PanelBottom },
  { name: "World", icon: Mountain },
  { name: "Accessibility", icon: Accessibility },
  { name: "Misc", icon: Wrench },
];
export const modules = [
  {
    name: "Shaders",
    description: "A different light on familiar worlds.",
    category: "Visuals",
    icon: Sparkles,
    tag: "Appearance",
  },
  {
    name: "Better Clouds",
    description: "A little more depth above the horizon.",
    category: "Visuals",
    icon: Cloud,
  },
  {
    name: "Zoom",
    description: "Bring the details a little closer.",
    category: "Visuals",
    icon: ZoomIn,
    key: "C",
  },
  {
    name: "Motion Blur",
    description: "A softer sense of movement.",
    category: "Visuals",
    icon: Waves,
  },
  {
    name: "Fullbright",
    description: "Adjust scene brightness for clarity.",
    category: "Visuals",
    icon: Sun,
  },
  {
    name: "Free Look",
    description: "Look around without changing direction.",
    category: "Visuals",
    icon: Eye,
    key: "ALT",
  },
  {
    name: "Replay Tools",
    description: "Keep a new perspective on your story.",
    category: "Visuals",
    icon: Film,
  },
  {
    name: "Screenshot Mode",
    description: "Frame the moment. Hide the distractions.",
    category: "Visuals",
    icon: Camera,
    key: "F2",
  },
  {
    name: "Ambient Fog",
    description: "Atmosphere, from dawn to dusk.",
    category: "Visuals",
    icon: Image,
  },
  {
    name: "Dynamic Lighting",
    description: "Let the things you carry light the way.",
    category: "Visuals",
    icon: Lightbulb,
  },
  {
    name: "FPS Boost",
    description: "Review compatible optimization options.",
    category: "Performance",
    icon: Zap,
  },
  {
    name: "Smart Animation",
    description: "Pause nonessential background motion.",
    category: "Performance",
    icon: Activity,
  },
  {
    name: "Entity Optimizer",
    description: "Explore entity rendering preferences.",
    category: "Performance",
    icon: Users,
  },
  {
    name: "Chunk Tweaks",
    description: "Balance view distance and loading.",
    category: "Performance",
    icon: Boxes,
  },
  {
    name: "Particle Limiter",
    description: "Choose how much detail fills the air.",
    category: "Performance",
    icon: WandSparkles,
  },
  {
    name: "Memory Cleaner",
    description: "Inspect memory tools before enabling.",
    category: "Performance",
    icon: MemoryStick,
  },
  {
    name: "UI Simplification",
    description: "Reduce blur and decorative effects.",
    category: "Performance",
    icon: Layers,
  },
  {
    name: "Coordinates",
    description: "A quiet reminder of where you are.",
    category: "HUD",
    icon: MapPin,
  },
  {
    name: "Armor Status",
    description: "Keep an eye on your equipment.",
    category: "HUD",
    icon: Shield,
  },
  {
    name: "FPS / Ping",
    description: "Compact connection and frame readouts.",
    category: "HUD",
    icon: Gauge,
  },
  {
    name: "Potion Effects",
    description: "See active effects at a glance.",
    category: "HUD",
    icon: FlaskConical,
  },
  {
    name: "Minimal HUD",
    description: "Only the essentials, always readable.",
    category: "HUD",
    icon: Minus,
  },
  {
    name: "Direction Display",
    description: "Find your bearings without the clutter.",
    category: "HUD",
    icon: Compass,
  },
  {
    name: "Hotbar Customization",
    description: "Make room for your own play style.",
    category: "HUD",
    icon: PanelBottom,
  },
  {
    name: "World Atmosphere",
    description: "Preview a calmer world palette.",
    category: "World",
    icon: Mountain,
  },
  {
    name: "Readable Chat",
    description: "Adjust contrast and text spacing.",
    category: "Accessibility",
    icon: Accessibility,
  },
  {
    name: "Sound Captions",
    description: "Give important sounds a visible cue.",
    category: "Accessibility",
    icon: Volume2,
  },
  {
    name: "Keybind Hints",
    description: "Remember the controls that matter.",
    category: "Misc",
    icon: Keyboard,
  },
  {
    name: "Cursor Style",
    description: "A precise pointer that fits your theme.",
    category: "Misc",
    icon: MousePointer2,
  },
];
